### ISSUE TITLE
CommonMark Import error

### ISSUE THREAD

**Issue by akpierson** [sunainapai/makesite#13] opened 2018-10-29 22:31 UTC
On windows, i checked where you import CommonMark library as 
`import CommonMark` 

I got an error even though i had the lib installed. I changed it to all lowercase 
`import commonmark` 
and it fixed the issue. 

Just though you should know.

**Comment by PaperMountainStudio** [comment] 2018-11-15 16:42
Solved in #14. Just waiting to be merged.

**Comment by sunainapai** [comment] 2019-01-08 16:18
Hi @akpierson, Thank you for reporting this issue. This issue was caused by [commit 4ee43fb](https://github.com/rtfd/CommonMark-py/commit/4ee43fbfbc0e3c6f42b8ddb31f2d12cdc3d34c04) in CommonMark-py which removed a symbolic link named `CommonMark`.

I have now merged pull request #14 by @PaperMountainStudio which fixes this issue. Thank you, @PaperMountainStudio, for the fix.

**Closed by sunainapai** 2019-01-08 16:18 UTC
